nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

articles:
    type:     rest
    resource: AppBundle\Controller\ArticleController
